MvcWebUI/Models/CartListViewModel.cs
using Entities.DomainModels;

namespace MvcWebUI.Models
{
    public class CartListViewModel
    {
        public Cart Cart { get; set; }
    }
}

MvcWebUI/Models/CategoryListViewModel.cs
using Entities.Concrete;

namespace MvcWebUI.Models
{
    public class CategoryListViewModel
    {

        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }

    }
}

MvcWebUI/Models/ErrorViewModel.cs
namespace MvcWebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcWebUI/Models/ProductListViewModel.cs
using Entities.Concrete;

namespace MvcWebUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products{ get; set; }
    }
}

MvcWebUI/Controllers/CartController.cs
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Helpers;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class CartController : Controller
    {

        private ICartService _cartService;
        private ICartSessionHelper _cartSessionHelper;
        private IProductService _productService;

        public CartController(ICartService cartService, ICartSessionHelper cartSessionHelper, IProductService productService)
        {
            _cartService = cartService;
            _cartSessionHelper = cartSessionHelper;
            _productService = productService;
        }

        public IActionResult AddToCart(int productId)
        {
            Product product = _productService.getById(productId);

            var cart = _cartSessionHelper.GetCart("cart");
            _cartService.AddToCart(cart,product);

            _cartSessionHelper.SetCart("cart",cart);


            return RedirectToAction("Index","Product");
        }

        public IActionResult Index() {

            var model = new CartListViewModel
            {
                Cart = _cartSessionHelper.GetCart("cart")
            };

            return View(model);

        }

        public IActionResult RemoveFromCart(int productId)
        {
            Product product = _productService.getById(productId);
            var cart = _cartSessionHelper.GetCart("cart");

            _cartService.RemoveFromCart(cart, productId);
            _cartSessionHelper.SetCart("cart",cart);

            return RedirectToAction("Index", "Cart");

        }
    }
}

MvcWebUI/Controllers/CategoryController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class CategoryController : Controller
    {


        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

    }
}

MvcWebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;
using System.Diagnostics;

namespace MvcWebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcWebUI/Controllers/ProductController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService= productService;
        }


        
        public IActionResult Index(int category)
        {
            var model = new ProductListViewModel
            {
                Products = category > 0 ? _productService.GetByCategory(category) : _productService.GetAll()
            };
            return View(model);
        }
    }
}

MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MvcWebUI.Models;

namespace MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {

        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService= categoryService;
        }


        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

MvcWebUI/Views/Cart/Index.cshtml
@model CartListViewModel
@{
}


<h2>Sepet</h2>

<table class="table table-responsive">
    <thead>
            <tr>
                <th>Id</th>
                <th>Ürün Adı</th>
                <th>Açıklama</th>
                <th>Fiyat</th>
                <th>Stok Adeti</th>
                <th>Satış Adeti</th>
            </tr>
        </thead>
    @foreach (var cartLine in Model.Cart.CartLines)
    {
        
        <tbody>
            <tr>
                <td>@cartLine.Product.ProductId</td>
                <td>@cartLine.Product.ProductName</td>
                <td>@cartLine.Product.QuantityPerUnit</td>
                <td>@cartLine.Product.UnitPrice</td>
                <td>@cartLine.Product.UnitsInStock</td>
                <td>@cartLine.quantity</td>
                <td><a class="btn btn-sm btn-danger" asp-action="RemoveFromCart" asp-controller="Cart" asp-route-productId="@cartLine.Product.ProductId">Sepetten Sil</a></td>
            </tr>
        </tbody>
    }
</table>

MvcWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcWebUI/Views/Product/Index.cshtml
@model ProductListViewModel


@{
}

<h2>Product List</h2>

<table class="table table-responsive">
    @foreach(var product in Model.Products)
    {
        <tr>
            <td>@product.ProductId</td>
            <td>@product.ProductName</td>
            <td>@product.QuantityPerUnit</td>
            <td>@product.UnitPrice</td>
            <td>@product.UnitsInStock</td>
            <td><a class="btn btn-sm btn-success" asp-action="AddToCart" asp-controller="Cart" asp-route-productId="@product.ProductId">Sepete Ekle</a></td>
        </tr>
    }
</table>

MvcWebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel
@{
}

<h2>Category List</h2>
<ul class="list-group">
    
    @{
        var titCss = "list-group-item";
        if (Model.CurrentCategory == 0)
            titCss += " active";
        <a href="/product/index" class="@titCss">Tümü Ürünler</a>
    }
    
    
    @foreach(var cat in Model.Categories)
    {
        var css = "list-group-item";
        if (cat.CategoryId == Model.CurrentCategory)
            css += " active";
        <a href="/product/index?category=@cat.CategoryId" class="@css">@cat.CategoryName</a>
    }
</ul>

MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcWebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcWebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-3">
                    @await Component.InvokeAsync("CategoryList")
                </div>
                <div class="col-9">@RenderBody()</div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>